class Marquee { //initialize a class called Marquee
  constructor(marquee) { //instance constructor function, which will take an HTML element as input
    this.marquee = marquee; //we want things to be created on default, so we set our constructor to do some things upon instance
    this.marqueeContent = document.createElement("ul");//creating ul
    this.marquee.appendChild(this.marqueeContent);//appending marquee content to marquee div
    this.marqueeContent.className = "marquee-content";//setting class to apply all CSS for marquee content
  }

  async getSymbolsFromServer() { //method to get symbol from server, which will be called in another method
    const response = await fetch(`${baseUrl}/company/stock/list`);
    const data = await response.json();
    return data.symbolsList.splice(0, 100);//creates an array made up of the first 100 removed items from data response array
  }

  async displayMarquee(){
    const list = await this.getSymbolsFromServer(); //call
    const items = list.map(item => `<li>${item.symbol} - $${item.price}</li>`).join('') 
    //items is an array that takes every element from the array generated by the getSymbolsFromServer method, converts it to HTML
    //and with the join method turns it into a string
    this.marqueeContent.innerHTML = items; //adds the inner HTML to ul and displays the marquee 
  }
}

